# Site settings
name: Less Or More
email: 41723031@xs.ustb.edu.cn
author: Mars
url: https://github.com/himyue/
resume_site: https://github.com/himyue/
github: https://github.com/himyue/
baseurl: ""
description: Actually, less is more!
meta_description: 马跃;个人博客;生命不止;折腾不休;看清生活;热爱生活
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: himyue

# Build settings
markdown: kramdown

# baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

plugins: [jekyll-paginate]